/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdsa_cw2_t1;

import java.awt.Toolkit;

/**
 *
 * @author ASUS
 */
public class Last_Page extends javax.swing.JFrame {

    /**
     * Creates new form Last_Page
     */
    public Last_Page() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("missile_64px.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblclose = new javax.swing.JLabel();
        lblmap = new javax.swing.JLabel();
        lblmap1 = new javax.swing.JLabel();
        lblmap2 = new javax.swing.JLabel();
        lblmap3 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Missile Simulation");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(null);

        lblclose.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblclose.setForeground(new java.awt.Color(255, 184, 0));
        lblclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdsa_cw2_t1/delete_32px.png"))); // NOI18N
        lblclose.setToolTipText("");
        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblclose);
        lblclose.setBounds(1021, 12, 32, 32);

        lblmap.setBackground(new java.awt.Color(102, 102, 102));
        lblmap.setForeground(new java.awt.Color(204, 204, 204));
        lblmap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdsa_cw2_t1/Untitled design (2).png"))); // NOI18N
        jPanel1.add(lblmap);
        lblmap.setBounds(0, 0, 605, 615);

        lblmap1.setBackground(new java.awt.Color(102, 102, 102));
        lblmap1.setFont(new java.awt.Font("Consolas", 1, 65)); // NOI18N
        lblmap1.setForeground(new java.awt.Color(204, 204, 204));
        lblmap1.setText("Level");
        jPanel1.add(lblmap1);
        lblmap1.setBounds(750, 210, 190, 82);

        lblmap2.setBackground(new java.awt.Color(102, 102, 102));
        lblmap2.setFont(new java.awt.Font("Consolas", 1, 70)); // NOI18N
        lblmap2.setForeground(new java.awt.Color(204, 204, 204));
        lblmap2.setText("Complete");
        jPanel1.add(lblmap2);
        lblmap2.setBounds(690, 320, 328, 89);

        lblmap3.setBackground(new java.awt.Color(102, 102, 102));
        lblmap3.setFont(new java.awt.Font("Consolas", 1, 75)); // NOI18N
        lblmap3.setForeground(new java.awt.Color(204, 204, 204));
        lblmap3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdsa_cw2_t1/Missile Simulation.png"))); // NOI18N
        jPanel1.add(lblmap3);
        lblmap3.setBounds(570, 100, 510, 55);

        btnhome.setBackground(new java.awt.Color(198, 18, 18));
        btnhome.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setText("Main Menu");
        btnhome.setBorder(null);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome);
        btnhome.setBounds(710, 460, 260, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1065, 615));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblcloseMouseClicked

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Last_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Last_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Last_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Last_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Last_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblclose;
    private javax.swing.JLabel lblmap;
    private javax.swing.JLabel lblmap1;
    private javax.swing.JLabel lblmap2;
    private javax.swing.JLabel lblmap3;
    // End of variables declaration//GEN-END:variables
}
