/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdsa_cw2_t1;

import java.awt.Toolkit;

/**
 *
 * @author ASUS
 */
public class Map2 extends javax.swing.JFrame {

    /**
     * Creates new form Map2
     */
    public Map2() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("missile_64px.png")));
        
        btnb.setEnabled(false);
        btnc.setEnabled(false);
        btnd.setEnabled(false);
        btne.setEnabled(false);
        btnlaunch.setEnabled(false);
        btnreset.setEnabled(false);
    }
    
    public static int MapNum,distancecount,c=0,b=0,r=0,d=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblclose = new javax.swing.JLabel();
        lblmap = new javax.swing.JLabel();
        btna = new javax.swing.JButton();
        btnb = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        btnd = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnlaunch = new javax.swing.JButton();
        lblmapname = new javax.swing.JLabel();
        btne = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Missile Simulation");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));

        lblclose.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblclose.setForeground(new java.awt.Color(255, 184, 0));
        lblclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdsa_cw2_t1/delete_32px.png"))); // NOI18N
        lblclose.setToolTipText("");
        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
        });

        lblmap.setBackground(new java.awt.Color(102, 102, 102));
        lblmap.setForeground(new java.awt.Color(204, 204, 204));
        lblmap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdsa_cw2_t1/A (1).png"))); // NOI18N

        btna.setBackground(new java.awt.Color(51, 51, 51));
        btna.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btna.setForeground(new java.awt.Color(255, 255, 255));
        btna.setText("A");
        btna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaActionPerformed(evt);
            }
        });

        btnb.setBackground(new java.awt.Color(51, 51, 51));
        btnb.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnb.setForeground(new java.awt.Color(255, 255, 255));
        btnb.setText("B");
        btnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbActionPerformed(evt);
            }
        });

        btnc.setBackground(new java.awt.Color(51, 51, 51));
        btnc.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnc.setForeground(new java.awt.Color(255, 255, 255));
        btnc.setText("C");
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });

        btnd.setBackground(new java.awt.Color(51, 51, 51));
        btnd.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnd.setForeground(new java.awt.Color(255, 255, 255));
        btnd.setText("D");
        btnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(51, 51, 51));
        btnreset.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("Reset(1)");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnlaunch.setBackground(new java.awt.Color(198, 18, 18));
        btnlaunch.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnlaunch.setForeground(new java.awt.Color(255, 255, 255));
        btnlaunch.setText("LAUNCH");
        btnlaunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaunchActionPerformed(evt);
            }
        });

        lblmapname.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblmapname.setForeground(new java.awt.Color(255, 255, 255));
        lblmapname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdsa_cw2_t1/up (2).png"))); // NOI18N

        btne.setBackground(new java.awt.Color(51, 51, 51));
        btne.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btne.setForeground(new java.awt.Color(255, 255, 255));
        btne.setText("E");
        btne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblmapname)
                        .addGap(201, 201, 201)
                        .addComponent(lblclose)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btna, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btne, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnreset)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnlaunch, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(353, 353, 353))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblclose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(lblmapname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblmap, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btna)
                    .addComponent(btnb)
                    .addComponent(btnc)
                    .addComponent(btnd)
                    .addComponent(btnreset)
                    .addComponent(btne))
                .addGap(18, 18, 18)
                .addComponent(btnlaunch)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1065, 615));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblcloseMouseClicked

    private void btnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaActionPerformed
        // TODO add your handling code here:
        distancecount = 0;
        btna.setBackground(java.awt.Color.gray);
        btna.setEnabled(false);
        btnb.setEnabled(true);
        btnc.setEnabled(true);
        if(r==0)
        {
            btnreset.setEnabled(true);
        }
    }//GEN-LAST:event_btnaActionPerformed

    private void btnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbActionPerformed
        // TODO add your handling code here:
        b=1;
        if(c==1)
        {
            distancecount = distancecount+3;
        }
        else
        {
            distancecount = distancecount+7;
        }
        btnb.setBackground(java.awt.Color.gray);
        btnb.setEnabled(false);
        if(d!=1)
        {
            btnd.setEnabled(true);
        }
        btne.setEnabled(true);
    }//GEN-LAST:event_btnbActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        // TODO add your handling code here:
        c=1;
        if(b==1)
        {
            distancecount = distancecount+3;
        }
        else
        {
            distancecount = distancecount+5;
        }
        btnc.setBackground(java.awt.Color.gray);
        btnc.setEnabled(false);
        btnd.setEnabled(true);
    }//GEN-LAST:event_btncActionPerformed

    private void btndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndActionPerformed
        // TODO add your handling code here:
        d=1;
        distancecount = distancecount+4;
        btnd.setBackground(java.awt.Color.gray);
        btnd.setEnabled(false);
        btnc.setEnabled(false);
        btne.setEnabled(true);
    }//GEN-LAST:event_btndActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        b=0;
        r=1;
        c=0;
        d=0;
        distancecount=0;
        btna.setBackground(java.awt.Color.darkGray);
        btnb.setBackground(java.awt.Color.darkGray);
        btnc.setBackground(java.awt.Color.darkGray);
        btnd.setBackground(java.awt.Color.darkGray);
        btne.setBackground(java.awt.Color.darkGray);
        btnb.setEnabled(false);
        btne.setEnabled(false);
        btna.setEnabled(true);
        btnc.setEnabled(false);
        btnd.setEnabled(false);
        btnlaunch.setEnabled(false);
        btnreset.setEnabled(false);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnlaunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaunchActionPerformed
        // TODO add your handling code here:

        int graph[][]=new int[][]{{0,7,5,0,0},{7,0,3,4,6},{5,3,0,4,0},{0,4,4,0,6},{0,6,0,6,0}};
        int visited[]=new int[5];
        int min=999,nexnode=0;
        int pred[]=new int[5]; //previous node
        int distance[]=new int[5];

        for(int i=0;i<5;i++)
        {
            visited[i]=0;
            pred[i]=0;
            for(int j=0;j<5;j++)
            {
                if(graph[i][j]==0)
                {
                    graph[i][j]=999;
                }
            }
        }

        distance=graph[0];
        visited[0]=1;
        distance[0]=0;

        for(int counter=0;counter<5;counter++)
        {
            min=999;
            for(int i=0;i<5;i++)
            {
                if(min>distance[i]&&visited[i]!=1)
                {
                    min=distance[i];
                    nexnode=i;
                }
            }

            visited[nexnode]=1;

            for(int i=0;i<5;i++)
            {
                if(visited[i]!=1)
                {
                    if(min+graph[nexnode][i]<distance[i])
                    {
                        distance[i]=min+graph[nexnode][i];
                    }
                }
            }
        }

        int shortestdis = 0;

        for(int i=0;i<5;i++)
        {
            shortestdis = distance[i];
        } 
        
        MapNum = 1;
        
        if(shortestdis == distancecount)
        {
            b=0;r=0;c=0;d=0;
            btna.setEnabled(false);
            btnb.setEnabled(false);
            btnc.setEnabled(false);
            btnd.setEnabled(false);
            btne.setEnabled(false);
            btnlaunch.setEnabled(false);
            btnreset.setEnabled(false);

            MBox1 mBox1 = new MBox1();
            mBox1.setVisible(true);
            this.dispose();
        }
        else
        {
            b=0;r=0;c=0;d=0;
            btna.setEnabled(false);
            btnb.setEnabled(false);
            btnc.setEnabled(false);
            btnd.setEnabled(false);
            btne.setEnabled(false);
            btnlaunch.setEnabled(false);
            btnreset.setEnabled(false);

            MBoxFail mBox2 = new MBoxFail();
            mBox2.setVisible(true);
            this.dispose();
        }
        btnreset.setEnabled(false); 
    }//GEN-LAST:event_btnlaunchActionPerformed

    private void btneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneActionPerformed
        // TODO add your handling code here:
        distancecount = distancecount+6;
        btne.setBackground(java.awt.Color.gray);
        btnlaunch.setEnabled(true);
        btna.setEnabled(false);
        btnb.setEnabled(false);
        btnc.setEnabled(false);
        btnd.setEnabled(false);
        btne.setEnabled(false);
    }//GEN-LAST:event_btneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Map2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Map2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Map2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Map2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Map2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btna;
    private javax.swing.JButton btnb;
    private javax.swing.JButton btnc;
    private javax.swing.JButton btnd;
    private javax.swing.JButton btne;
    private javax.swing.JButton btnlaunch;
    private javax.swing.JButton btnreset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblclose;
    private javax.swing.JLabel lblmap;
    private javax.swing.JLabel lblmapname;
    // End of variables declaration//GEN-END:variables
}
